spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/work
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
    properties:
      useSSL: false

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

